### ISSUE TITLE
Autoloading usage of org-export-define-backend causing issues

### ISSUE THREAD

**Issue by ghost** [dantecatalfamo/ox-ssh#2]
Hi :wave: I started using this package and I love it!

I'm having an issue with the autoload cookie for usage of `org-export-define-backend` was added in [this commit.](https://github.com/dantecatalfamo/ox-ssh/commit/62f4a19cf85df76b2936e584ed5e8d313917f593)

I was going to submit a PR to remove it, because for me when I generate my autoload file it gives me an error, because the function `org-export-define-backend` is not also autoloaded, so the definer fails when I load my autoloads.   

I don't understand why it should to be autoloaded in the first place, so I'm asking why it's there and if there isn't a particular reason if it can be removed.

**Comment by dantecatalfamo** [comment]
Hey, I'm glad you're liking the package! :slightly_smiling_face: 

I don't remember why I added it, and I believe you're right. It's probably an improper use of `autoload`. I removed it in a [recent commit](https://github.com/dantecatalfamo/ox-ssh/commit/1b39849e3a315de95543eb3cf69c42fa33a8f5cd). Hope this fixes the issue.

**Comment by ghost** [comment]
That fixes it! Thank you :slightly_smiling_face:!
